### PR TITLE
Fixed test of WpConfigSplitter

### LINKED ISSUE #953: Put a comment to wp-config.common.php
`wp-config.common.php` is empty most of the time and users might be wondering what this file is. We should put a small comment there.

### PR DESCRIPTION
**Pull request by octopuss**
Resolves #953 .

Reviewers:

- [x] @JanVoracek 

thank you.

### CODE REVIEW

File: plugins/versionpress/tests/Unit/WpConfigSplitterTest.php [hunk 1]
```diff
@@ -102,6 +102,8 @@ class WpConfigSplitterTest extends \PHPUnit_Framework_TestCase
 
     private $commonConfig = <<<'DOC'
 <?php
+// Configuration common to all VersionPress environments, included from `wp-config.php`.
+// Learn more at https://docs.versionpress.net/en/getting-started/configuration
```
Comment (borekb) [inline plugins/versionpress/tests/Unit/WpConfigSplitterTest.php]: It would be safer to load this from the template file, not hardcode it here.
