### PR TITLE
Fixed deserialization when serialized string is starting with HTML tag

### LINKED ISSUE #1002: Serialized postmeta values are not saved in new format
Related: #619.

Complex serialized values are not correctly transferred to a new storage format for ini files.

Example from database (stored in serialized format in ini file):

```
a:4:{s:13:"571f987e414a5";O:8:"stdClass":5:{s:4:"node";s:13:"571f987e414a5";s:4:"type";s:3:"row";s:6:"parent";N;s:8:"position";i:0;s:8:"settings";O:8:"stdClass":47:{s:5:"width";s:5:"fixed";s:13:"content_width";s:5:"fixed";s:11:"full_height";s:7:"default";s:10:"text_color";s:0:"";s:10:"link_color";s:0:"";s:11:"hover_color";s:0:"";s:13:"heading_color";s:0:"";s:7:"bg_type";s:5:"color";s:8:"bg_image";s:0:"";s:9:"bg_repeat";s:9:"no-repeat";s:11:"bg_position";s:13:"center center";s:13:"bg_attachment";s:6:"scroll";s:7:"bg_size";s:5:"cover";s:8:"bg_video";s:0:"";s:13:"bg_video_webm";s:0:"";s:17:"bg_video_fallback";s:0:"";s:9:"ss_source";s:9:"wordpress";s:9:"ss_photos";s:0:"";s:11:"ss_feed_url";s:0:"";s:8:"ss_speed";s:1:"3";s:13:"ss_transition";s:4:"fade";s:21:"ss_transitionDuration";s:1:"1";s:12:"ss_randomize";s:5:"false";s:17:"bg_parallax_image";s:0:"";s:17:"bg_parallax_speed";s:1:"2";s:8:"bg_color";s:6:"dc1818";s:10:"bg_opacity";s:3:"100";s:16:"bg_overlay_color";s:0:"";s:18:"bg_overlay_opacity";s:2:"50";s:11:"border_type";s:0:"";s:12:"border_color";s:0:"";s:14:"border_opacity";s:3:"100";s:10:"border_top";s:1:"1";s:13:"border_bottom";s:1:"1";s:11:"border_left";s:1:"0";s:12:"border_right";s:1:"0";s:10:"margin_top";s:0:"";s:13:"margin_bottom";s:0:"";s:11:"margin_left";s:0:"";s:12:"margin_right";s:0:"";s:11:"padding_top";s:0:"";s:14:"padding_bottom";s:0:"";s:12:"padding_left";s:0:"";s:13:"padding_right";s:0:"";s:18:"responsive_display";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";}}s:13:"571f987e6760e";O:8:"stdClass":5:{s:4:"node";s:13:"571f987e6760e";s:4:"type";s:12:"column-group";s:6:"parent";s:13:"571f987e414a5";s:8:"position";i:0;s:8:"settings";s:0:"";}s:13:"571f987e679f6";O:8:"stdClass":5:{s:4:"node";s:13:"571f987e679f6";s:4:"type";s:6:"column";s:6:"parent";s:13:"571f987e6760e";s:8:"position";i:0;s:8:"settings";O:8:"stdClass":1:{s:4:"size";i:100;}}s:13:"571f987e98b29";O:8:"stdClass":5:{s:4:"node";s:13:"571f987e98b29";s:4:"type";s:6:"module";s:6:"parent";s:13:"571f987e679f6";s:8:"position";i:0;s:8:"settings";O:8:"stdClass":11:{s:4:"text";s:994:"<p>This is an example page. It's different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>
<blockquote><p>Hi there! I'm a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin' caught in the rain.)</p></blockquote>
<p>...or something like this:</p>
<blockquote><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>
<p>As a new WordPress user, you should go to <a href="http://localhost/wp427/wordpress/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>
";s:10:"margin_top";s:0:"";s:13:"margin_bottom";s:0:"";s:11:"margin_left";s:0:"";s:12:"margin_right";s:0:"";s:18:"responsive_display";s:0:"";s:9:"animation";s:0:"";s:15:"animation_delay";s:3:"0.0";s:2:"id";s:0:"";s:5:"class";s:0:"";s:4:"type";s:9:"rich-text";}}}
```

### PR DESCRIPTION
**Pull request by octopuss**
Resolves #1002 .

Also fix of incorrect computation of the string length when it contains newlines.

Reviewers:

- [x] @JanVoracek 

Thank you.

### CODE REVIEW

File: plugins/versionpress/tests/Unit/IniSerializerTest.php [hunk 1]
```diff
@@ -829,6 +829,52 @@ public function serializedArrayWithEscapedSpecialStrings()
...
+        $this->assertSame($data, IniSerializer::deserialize($ini));
+        
+    }
+
+    /**
+     * @test
+     */
+    public function serializedStringWithNewLines()
+    {
+        $arrayWithHtml = ["meta_key" => "who_is_the_best", "meta_value" => "VersionPress\r\nis\r\nthe\r\nbest"];
```
Comment (JanVoracek) [inline plugins/versionpress/tests/Unit/IniSerializerTest.php]: Copy&Paste bug :) wrong name

File: plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php [hunk 2]
```diff
@@ -259,6 +259,12 @@ private static function convertValueToSerializedString($value, $relatedLines = [
     {
         $type = null; // string or number
 
+        //@see IniSerializer::getReplacedEolString
```
Comment (JanVoracek) [inline plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php]: Formatting. Missing space after `//`.

File: plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php [hunk 3]
```diff
@@ -259,6 +259,12 @@ private static function convertValueToSerializedString($value, $relatedLines = [
...
+        $eolReplacement = [
```
Comment (JanVoracek) [inline plugins/versionpress/src/Storages/Serialization/SerializedDataToIniConverter.php]: I think it's not a good idea to have the placeholders duplicated here. What about removing the placeholders before `SerializedDataToIniConverter::fromIniLines`?
