### PR TITLE
--allow-root for nested WP-CLI commands

### LINKED ISSUE #1049: Apply-changes doesn't pass allow-root
WP-CLI complains when running as root 

>  Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.
> 
> If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
> 
> If you'd like to continue as root, please run this again, adding this flag:  --allow-root
> 
> If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
> 
> ```
> sudo -u USER -i -- wp <command>
> ```

Their "sudo" work around seems to be buggy too. 
"wp vp apply-changes" doesn't pass the "--allow-root" flag.

> root@host [2570 15:10:31 /******_/**_*****]# wp vp apply-changes --allow-root
> Error: Maintenance mode couldn't be switched. Details:
> 
> Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

### PR DESCRIPTION
**Pull request by JanVoracek**
Resolves #1049.

I think we can add the switch to all commands, no matter they were run under root or not. Commands running under standard user do not mind the `--allow-root` switch.

### CODE REVIEW

File: plugins/versionpress/src/Cli/VPCommandUtils.php [hunk 1]
```diff
@@ -23,6 +23,9 @@ public static function runWpCliCommand($command, $subcommand, $args = [], $cwd =
             $args['color'] = null;
         }
 
+        // For commands that were run under root - #1049
+        $args['--allow-root'] = null;
```
Comment (borekb) [inline plugins/versionpress/src/Cli/VPCommandUtils.php]: This was actually not correct, fixed in https://github.com/versionpress/versionpress/pull/1272/commits/ceca06332d2d2ca6f8cfd6999e5d5526542f210c.
