### PR TITLE
Image edit not versioned

### LINKED ISSUE #877: Uncommitted changes for edited images
Steps to reproduce:

1) Upload any image.
2) Select this image and click "Edit Image" button bellow image.
3) Make any changes, for example rotate image a little bit :-)
4) Click "Save" and return to VersionPress - you will have some uncommitted changes.

You can make another change, for example delete another image and these changes will be automatically committed inside this unrelated commit.

### PR DESCRIPTION
**Pull request by octopuss**
Resolves #877 .

It adds new hook to WordPress. Please think about it carefully. Maybe you will find better solution.

Reviewers:

- [x] @JanVoracek 

Thank you.

### CODE REVIEW

File: plugins/versionpress/versionpress.php [hunk 1]
```diff
@@ -291,6 +291,12 @@ function _vp_get_language_name_by_code($code) {
 
     add_action('set_object_terms', vp_create_update_post_terms_hook($mirror, $vpidRepository));
 
+    add_filter('wp_save_image_editor_file', function ($saved, $filename, $image, $mime_type, $post_id) use ($vpidRepository, $committer){
+        $vpid = $vpidRepository->getVpidForEntity('post',$post_id);
```
Comment (JanVoracek) [inline plugins/versionpress/versionpress.php]: Formatting
